# Allow to cache content generation.
cache:
  enable: false

# Remove unnecessary files after hexo generate.
minify: true

# 布局方案选择
#scheme: Muse
scheme: Mist
#scheme: Pisces
#scheme: Gemini

# 主题暗色模式
# 白天/夜间自动开启亮色/暗色模式
darkmode: true

# 知识共享许可证
creative_commons:
  license: by-nc-sa
  sidebar: true
  post: false
  language: deed.zh


# 侧边栏样式
sidebar:
  position: right
avatar:
  url: /uploads/avatar.jpg
  rounded: true
social:
  GitHub: https://github.com/fzxiang || fab fa-github
  E-Mail: mailto:848026280@qq.com || fa fa-envelope
  Weibo: https://weibo.com/18850105062 || fab fa-weibo

auto_excerpt:
  enable: true
  length: 150


# 网站底部配置
footer:
  since: 2021
  copyright: Copyright Alson
  powered: false

#  beian:
#    enable: true
#    icp: 京ICP备 1234567890号-1
#    gongan_id: 1234567890
#    gongan_num: 京公网安备 1234567890号
#    gongan_icon_url: /uploads/beian.png



# 菜单
# 除了主页(home)和存档(archives)，菜单部分下的所有自定义页面都需要手动创建。
# 参见https://theme-next.js.org/docs/theme-settings/custom-pages.html
# 此外，支持网站地图还需要hexo-generator-sitemap插件。
# https://github.com/hexojs/hexo-generator-sitemap
menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #commonweal: /404/ || fa fa-heartbeat
  sitemap: /sitemap.xml || fa fa-sitemap
  # about: /about/ || fa fa-user
#  Docs:
#    default: /docs/ || fa fa-book
#    Getting Started:
#      default: /getting-started/ || fa fa-flag
#      Installation: /installation.html || fa fa-download
#      Configuration: /configuration.html || fa fa-wrench
#    Third Party Services:
#      default: /third-party-services/ || fa fa-puzzle-piece
#      Math Equations: /math-equations.html || fa fa-square-root-alt
#      Comment Systems: /comments.html || fa fa-comment-alt


### 第三方服务插件 ###

# Pjax
# 使用AJAX加载页面，并使用pushState()更新浏览器的当前URL，
# 而不需要重新加载页面的布局或任何资源（JS，CSS），从而提供一个快速的页面加载。
# https://github.com/next-theme/pjax
pjax: true


# Comment Systems
# 多重评论系统 changyan | disqus | disqusjs | facebook_comments_plugin | gitalk | livere | valine | vkontakte
# 使用Gitalk 链接Github Issue API  https://gitalk.github.io
gitalk:
  enable: false
  github_id:  fzxiang
  repo:  blog
  client_id:  fae14697bc89bf85bf1c
  client_secret:  cf6f70343e2df3be83d2e5dd7d33d04302ea8f28
  admin_user:  fzxiang
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available value: en, es-ES, fr, ru, zh-CN, zh-TW
  language: zh-CN


# Local search
# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: true
  # If auto, 通过改变输入来触发搜索。
  # If manual, 则通过按回车键或搜索键触发搜索。
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # 将 html 字符串解压缩为可读的字符串。
  unescape: true
  # 在页面加载时预加载搜索数据。
  preload: true


# Tidio Support Chat Services
# See: https://www.tidio.com
# Dashboard: https://www.tidio.com/panel/dashboard
tidio:
  enable: true
  key: lhyddet8opk3sbgybb3rqgfeyfjmshwg

# 在侧边栏中打开指定聊天小部件的按钮。
# 首先，你需要启用你想要的聊天服务来激活它的侧边栏按钮
chat:
  enable: false
  service: tidio
  icon: fa fa-comment
  text: 与我联系


# Preview
preview:
  enable: true
  model: wave  # wave cloud
  background:
    default: /images/theme/welcome-image.jpg
    api: # https://source.unsplash.com/random/1920x1080
    size: cover # css: background-size
    position: center # css: background-position
  motto:
    color: '#ffffff'
    default: 我在开了灯的床头下，想问问自己的心啊。
    api: https://v1.hitokoto.cn/?encode=text&c=d


custom_file_path:
  head: source/_data/head.njk
  #header: source/_data/header.njk
  #sidebar: source/_data/sidebar.njk
  #postMeta: source/_data/post-meta.njk
  #postBodyEnd: source/_data/post-body-end.njk
  #footer: source/_data/footer.njk
  bodyEnd: source/_data/body-end.njk
  variable: source/_data/variables.styl
  #mixin: source/_data/mixins.styl
  style: source/_data/styles.styl


# Show multilingual switcher in footer.
language_switcher: true

# 在主题配置文件中设置copy_button.enable为true来启用它。
# All available themes: https://theme-next.js.org/highlight/
# 默认情况下，NexT会显示复制和粘贴功能的结果。
codeblock:
  theme:
    light: default
    dark: tomorrow-night
  prism:
    light: prism
    dark: prism-dark
  copy_button:
    enable: true
