# Allow to cache content generation.
cache:
  enable: false

# Remove unnecessary files after hexo generate.
minify: true

# 布局方案选择
#scheme: Muse
scheme: Mist
#scheme: Pisces
#scheme: Gemini

# 主题暗色模式
# 白天/夜间自动开启亮色/暗色模式
darkmode: true

# 知识共享许可证
creative_commons:
  license: by-nc-sa
  sidebar: true
  post: true
  language: deed.zh


# 菜单
# 除了主页(home)和存档(archives)，菜单部分下的所有自定义页面都需要手动创建。
# 参见https://theme-next.js.org/docs/theme-settings/custom-pages.html
# 此外，支持网站地图还需要hexo-generator-sitemap插件。
# https://github.com/hexojs/hexo-generator-sitemap
menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  #tags: /tags/ || fa fa-tags
  #categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat
  Docs:
    default: /docs/ || fa fa-book
    Getting Started:
      default: /getting-started/ || fa fa-flag
      Installation: /installation.html || fa fa-download
      Configuration: /configuration.html || fa fa-wrench
    Third Party Services:
      default: /third-party-services/ || fa fa-puzzle-piece
      Math Equations: /math-equations.html || fa fa-square-root-alt
      Comment Systems: /comments.html || fa fa-comment-alt


### 第三方服务插件 ###

# Pjax
# 使用AJAX加载页面，并使用pushState()更新浏览器的当前URL，
# 而不需要重新加载页面的布局或任何资源（JS，CSS），从而提供一个快速的页面加载。
# https://github.com/next-theme/pjax
pjax: true


# Comment Systems
# 多重评论系统 changyan | disqus | disqusjs | facebook_comments_plugin | gitalk | livere | valine | vkontakte
# 使用Gitalk 链接Github Issue API  https://gitalk.github.io
gitalk:
  enable: true
  github_id:  fzxiang
  repo:  blog
  client_id:  fae14697bc89bf85bf1c
  client_secret:  cf6f70343e2df3be83d2e5dd7d33d04302ea8f28
  admin_user:  fzxiang
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available value: en, es-ES, fr, ru, zh-CN, zh-TW
  language: zh-CN


# Local search
# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: true
  # If auto, 通过改变输入来触发搜索。
  # If manual, 则通过按回车键或搜索键触发搜索。
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # 将 html 字符串解压缩为可读的字符串。
  unescape: true
  # 在页面加载时预加载搜索数据。
  preload: true


# Tidio Support Chat Services
# See: https://www.tidio.com
# Dashboard: https://www.tidio.com/panel/dashboard
tidio:
  enable: true
  key: lhyddet8opk3sbgybb3rqgfeyfjmshwg

# 在侧边栏中打开指定聊天小部件的按钮。
# 首先，你需要启用你想要的聊天服务来激活它的侧边栏按钮
chat:
  enable: true
  service: tidio
  icon: fa fa-comment
  text: 与我联系
